/*
This file was generated by the Surface compiler.
*/

import { subscribe } from "@github/paste-markdown";

export default {
  mounted() {
    subscribe(this.el);
  },
};

// assets/js/app.js
import "@github/markdown-toolbar-element";