/*
This file was generated by the Surface compiler.
*/

import 'emoji-picker-element';

const ReactionPicker = {
  mounted() {
    // const button = this.el.querySelector('.reaction-button');
    const picker = this.el.querySelector('emoji-picker');
    const objectId = this.el.dataset.objectId;
    console.log("CAZZZOOOOO")
    console.log(objectId)
    // Toggle picker visibility
    // button.addEventListener('click', () => {
    //   picker.classList.toggle('hidden');
    // });

    // Handle emoji selection
    picker.addEventListener('emoji-click', event => {
      const emoji = event.detail.unicode;
      
      // Send the reaction to the server
      this.pushEvent("Bonfire.Social.Likes:add_reaction", {
        emoji: emoji,
        id: objectId
      });
      
      // Hide the picker after selection
      picker.classList.add('hidden');
    });

    // Close picker when clicking outside
    // document.addEventListener('click', (event) => {
    //   if (!this.el.contains(event.target)) {
    //     picker.classList.add('hidden');
    //   }
    // });
  }
};

export default ReactionPicker;