##
#
# Utility structs
#
# These are common data structures used throughout the API
#
##

"""
The `URI` type simply declares a reference to an external web URL, Holochain entry or other resource.
"""
scalar URI

# """
# The `DateTime` scalar type represents a DateTime value as specified by
# [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).
# """
# scalar DateTime
